### ISSUE TITLE
Add `@admin.action` and `@admin.display`

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-upgrade#47]
### Description

Find functions with appropriate attributes being set and rewrite them to use `@admin.action` or `@admin.display` respectively

https://docs.djangoproject.com/en/3.2/ref/contrib/admin/actions/#django.contrib.admin.action
https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#django.contrib.admin.display

This is going to be a little tricky to do as multiple AST nodes will need inspecting and rewriting at once, if they all match.

We might need to visit class definitions and modules, and check all the function definitions within each + following assignments to figure out everything.

Steps:

- [x] module-level action functions - #178
- [x] class-level action functions - #197
- [x] module-level and class-level display functions - #199

**Comment by adamchainz** [comment]
@ngnpope check it out 😎

**Comment by ngnpope** [comment]
Amazing! 🌟 

Noticed one thing: This should also work for `from django.contrib.gis import admin`.

**Comment by adamchainz** [comment]
Ah, nicely spotted. I've also added that to the tasks for `@admin.register` in #190.
